# Generated by Django 4.1.3 on 2022-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0003_alter_announce_options_announce_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='county',
            field=models.CharField(max_length=100, verbose_name='Judet'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='description',
            field=models.TextField(verbose_name='Descriere'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Etaj'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.CharField(max_length=500, verbose_name='Imagine'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Localitate'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='price',
            field=models.FloatField(verbose_name='Pret'),
        ),
        migrations.AlterField(
            model_name='announce',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titlu'),
        ),
    ]
