# Generated by Django 4.1.3 on 2022-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0004_alter_announce_county_alter_announce_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagine'),
        ),
    ]
