# Generated by Django 4.1.3 on 2022-11-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0005_alter_announce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagine'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagine')),
                ('announce', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imobiliare.announce')),
            ],
        ),
    ]
